DEBUG = True
SERVER_HOST = '0.0.0.0'
SQLALCHEMY_ECHO = True
SQLALCHEMY_DATABASE_URI = "mysql://root:ubuntumysql0220@127.0.0.1:3306/food_db?charset=utf8mb4"
SQLALCHEMY_TRACK_MODIFICATIONS = True
# SQLALCHEMY_ENCODING = 'utf8mb4'
